### ISSUE TITLE
Improve docs for running multiple DPs on same host

### ISSUE THREAD

**Issue by jijiechen** [kumahq/kuma-website#1968] opened 2024-10-14 02:55 UTC
### What happened?

We need to improve our docs involving multiple DPs on a single host.

After the introduction of features that listen ports on the host, user may be encoutering issues of  port conflicting:
* Application probe proxy defaultly listens to `9001`
* Envoy readiness reporter defautly listens to `9902`

They have to configure these ports using environment variables before they launch instances of DPs:

```sh
export KUMA_READINESS_PORT=9903
export KUMA_APPLICATION_PROBE_PROXY_PORT=0
kuma-dp run
```

xref https://github.com/kumahq/kuma/issues/11769

**Comment by Icarus9913** [comment] 2024-10-14 03:11
The ENV `KUMA_READINESS_PORT ` comes from the structure [Dataplane](https://github.com/kumahq/kuma/blob/60c64cdea217e76b9f7f63c599828ebddc45426a/pkg/config/app/kuma-dp/config.go#L129-L142)
So, we may should expose **all of the properties ENV variables** of the structure to the docs?

**Comment by lahabana** [comment] 2024-10-18 21:38
Duplicate of https://github.com/kumahq/kuma-website/issues/1831

**Closed by lahabana** 2024-10-18 21:38 UTC
Labels: triage/pending, kind/bug
