### ISSUE TITLE
Add cloud-specific deployment instructions

### ISSUE THREAD

**Issue by manibh-kong** [kumahq/kuma-website#405] opened 2021-03-31 01:02 UTC
Recently I had a task to install Kuma in EKS cluster. I noticed that whether I have multi zone or standalone setup there are steps that are missing or hard to find in documentation. 
For example, in Amazon EKS installation one has to make sure to install following:
1- Kuma DNS: to resolve the virtual IPs
2- Kong Ingress controller: it can be misleading, one may try to use Kuma Ingress, but that's only for the cross zone communication and for Kuma internals and can not be used as ingress controller. Thus we should install Kong Ingress (DB Less) otherwise after enabling MTLS all Amazon NLB's will fail due to mTLS cert checking for SAN of NLB...
3- For multi zone setup, Kuma Ingress is also required.
4- Ingress resource sample / template that will be required in this case to allow traffic from outside of EKS cluster to micro services. 
I can contribute to create the initial draft of what needs to be installed / configured with some syntax.

**Comment by nickolaev** [comment] 2021-03-31 07:55
We have started an effort to gather this information for the Multi-zone setup here:
https://github.com/kumahq/kuma-website/pull/402

**Comment by lahabana** [comment] 2022-02-14 14:58
Worth keeping this issue in mind when tackling this: https://github.com/kumahq/kuma-website/issues/614

**Comment by lahabana** [comment] 2023-11-02 16:47
Do we still have anything cloud specific?

**Comment by slonka** [comment] 2024-02-07 10:25
@lahabana I recently came across this - https://github.com/kumahq/kuma-website/issues/1232

**Comment by lahabana** [comment] 2024-07-30 13:54
Duplicate of: https://github.com/kumahq/kuma-website/issues/1847 which has more info

**Closed by lahabana** 2024-07-30 13:54 UTC
Labels: triage/accepted, kind/improvement
