### ISSUE TITLE
Consider using minikube instead of kind in the guides

### ISSUE THREAD

**Issue by schogges** [kumahq/kuma-website#1959] opened 2024-10-11 10:41 UTC
### What happened?

While running the gateway it's not possible to reach the gateway ip from your local computer. It might not be an issue when using minikube. Consider changing if it works.

**Comment by lahabana** [comment] 2024-10-18 21:34
Duplicate of https://github.com/kumahq/kuma-website/issues/1649

**Closed by lahabana** 2024-10-18 21:34 UTC
Labels: triage/pending, kind/improvement
