### ISSUE TITLE
Clean up traffic metrics page

### ISSUE THREAD

**Issue by Bradamant3** [kumahq/kuma-website#524] opened 2021-08-31 20:15 UTC
The entire page is now only partly copyedited. Needs a full rework and thorough technical review for all the bits that haven't been touched in a long time.

**Comment by Bradamant3** [comment] 2021-11-29 21:22
See also #602

**Comment by lahabana** [comment] 2021-12-14 16:43
Duplicate of #602

**Closed by lahabana** 2021-12-14 16:43 UTC
Labels: triage/duplicated
