### ISSUE TITLE
Add Exposed Metrics and Details to the Metrics Page  

### ISSUE THREAD

**Issue by austince** [kumahq/kuma-website#439] opened 2021-05-14 17:18 UTC
Kuma has better out-of-the-box metrics for investigating traffic than Istio, but it is difficult to understand what metrics are actually exposed by looking at [Kuma's Metrics page](https://kuma.io/docs/1.1.6/policies/traffic-metrics/). It would be nice to do something like [Istio's Standard Metrics](https://istio.io/latest/docs/reference/config/metrics/#metrics), where some key metrics are listed and briefly explained.

**Comment by Bradamant3** [comment] 2021-05-14 17:31
Thanks for the suggestion @austince -- there's a project in the works to generate policy docs from the code, to provide this kind of detail. Would that address your suggestion?

**Comment by austince** [comment] 2021-05-14 19:54
Maybe – is it the project that's trying to generate docs from the protobufs? Or is there a project to do that for the entire codebase? Looking at [`metrics.proto`](https://github.com/kumahq/kuma/blob/5f26a3a5879d1250a9a3a2b3a109f8e70373c907/api/mesh/v1alpha1/metrics.proto), I'm not sure it would be addressed if it's the first case.

I'm looking for the actual metric names, so I could go about building my own dashboards without first setting up an environment and inspecting what's there, like:
* `envoy_response_code_class`
* `envoy_cluster_health_check_healthy` 
* `envoy_cluster_upstream_rq_total`

I can't find these documented in envoy anywhere 😞 but there's a decent example from [AWS CloudWatch](https://docs.aws.amazon.com/AmazonCloudWatch/latest/monitoring/ContainerInsights-Prometheus-metrics.html).

**Comment by lahabana** [comment] 2022-10-31 11:19
Duplicate of #1007

**Closed by lahabana** 2022-10-31 11:19 UTC
Labels: triage/accepted, kind/improvement
