### ISSUE TITLE
Missing docs for `MeshRetry` and `MeshHTTPRoute`

### ISSUE THREAD

**Issue by lobkovilya** [kumahq/kuma-website#2112] opened 2024-12-04 12:39 UTC
### What happened?

There is [an e2e test](https://github.com/kumahq/kuma/blob/fa008d1587e110d7dae97f9e1dca450e552be4b5/test/e2e_env/universal/meshretry/http.go#L250) but no docs

**Comment by lukidzi** [comment] 2024-12-09 15:36
duplicate of https://github.com/kumahq/kuma-website/issues/2110

**Closed by lukidzi** 2024-12-09 15:36 UTC
Labels: triage/accepted, kind/bug
